"use client";

import { Check, Copy, PenLine } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { toast } from "sonner";

import { ActivityFeed } from "@/components/chat/activity-feed";
import { Button } from "@/components/ui/button";
import { api } from "@/lib/api";
import { toRows } from "@/lib/activity";
import { Markdown } from "@/lib/markdown";
import type { AgentEvent, ChatMessage } from "@/lib/types";
import { useWorkspace } from "@/lib/workspace";

function titleFrom(content: string) {
  const heading = content.split("\n").find((line) => line.startsWith("# "));
  if (heading) return heading.replace(/^#\s+/, "").trim().slice(0, 160);
  return content.trim().split("\n")[0]?.slice(0, 160) || "Untitled document";
}

export function UserMessage({ message }: { message: ChatMessage }) {
  return (
    <div className="flex justify-end">
      <div className="max-w-[85%]">
        <div className="rounded-xl rounded-br-md border border-border bg-surface px-3.5 py-2.5 text-[0.9375rem] leading-relaxed shadow-xs">
          {message.content}
        </div>
      </div>
    </div>
  );
}

export function AssistantMessage({
  content,
  events,
  running,
  projectId,
}: {
  content: string;
  events: AgentEvent[];
  running: boolean;
  /** The project this conversation writes into; undefined means the caller's Workspace. */
  projectId?: string;
}) {
  const router = useRouter();
  const { refreshDocuments } = useWorkspace();
  const [copied, setCopied] = useState(false);
  const [exporting, setExporting] = useState(false);
  const rows = toRows(events);

  async function copy() {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 1600);
  }

  async function openInEditor() {
    setExporting(true);
    try {
      const document = await api.createFromMarkdown({
        title: titleFrom(content),
        markdown: content,
        commit_message: "Initial draft generated by aiper",
        project_id: projectId ?? null,
      });
      await refreshDocuments();
      // The response carries where it actually landed — the caller's Workspace
      // project when the conversation was not scoped to one.
      router.push(
        document.project_id
          ? `/projects/${document.project_id}/documents/${document.id}`
          : "/projects",
      );
    } catch (error) {
      toast.error("Could not open in the editor", {
        description: error instanceof Error ? error.message : undefined,
      });
    } finally {
      setExporting(false);
    }
  }

  return (
    <div className="space-y-3">
      {rows.length > 0 ? <ActivityFeed rows={rows} running={running} defaultOpen={running} /> : null}

      {content ? (
        <Markdown content={content} />
      ) : running ? (
        <div className="flex items-center gap-1.5 py-1">
          {[0, 1, 2].map((index) => (
            <span
              key={index}
              className="size-1.5 animate-pulse rounded-full bg-muted-foreground/50"
              style={{ animationDelay: `${index * 140}ms` }}
            />
          ))}
        </div>
      ) : null}

      {content && !running ? (
        <div className="flex items-center gap-1 pt-1">
          <Button variant="ghost" size="xs" onClick={copy}>
            {copied ? <Check className="text-verdict-pass" /> : <Copy />}
            {copied ? "Copied" : "Copy"}
          </Button>
          <Button variant="ghost" size="xs" onClick={openInEditor} loading={exporting}>
            <PenLine />
            Open in editor
          </Button>
        </div>
      ) : null}
    </div>
  );
}
