"""The scripted agent.

Emits the exact event shapes `backend/app/agents/runtime.py` produces — plans
with per-item status transitions, delegation rows, tool start/end pairs, then a
token-by-token answer.

The prose is scripted. The page numbers in it are not: they come from the same
page-per-chunk index the real retriever uses, which makes this a fair test of
ingestion, streaming, the activity feed and the editor import path.
"""

from __future__ import annotations

import asyncio
import re
import uuid
from collections.abc import AsyncIterator
from typing import Any

from app.store import PageChunk, Store, new_id

_TOOL_PAUSE = 0.42
_STEP_PAUSE = 0.22
_TOKEN_PAUSE = 0.012

FOOTER = (
    "\n\n---\n\n*Generated by the aiper mock backend. The prose is scripted; the "
    "file names, page numbers and retrieval scores above are real, read from your "
    "own uploaded documents.*\n"
)

_LABELS = {
    "read_file": "Reading workspace file",
    "write_file": "Writing workspace file",
    "list_templates": "Listing templates",
    "get_template": "Resolving the template",
    "search_pages": "Searching indexed pages",
    "comparison_scope": "Confirming comparison scope",
    "load_target_document": "Reading the target document",
    "find_evidence_in_sources": "Looking for evidence in the sources",
    "build_compliance_matrix": "Building compliance matrix",
}


def _citation(page: PageChunk) -> str:
    return f"[{page.filename}, p.{page.page}]"


def _excerpt(page: PageChunk, limit: int = 220) -> str:
    text = " ".join(page.text.split())
    return text if len(text) <= limit else f"{text[:limit]}…"


class Feed:
    """Collects the plan so each emission carries the full per-item status."""

    def __init__(self, items: list[str]) -> None:
        self.items = [{"content": text, "status": "pending"} for text in items]
        self.plan_id = str(new_id())

    def event(self) -> dict[str, Any]:
        return {"type": "plan", "id": self.plan_id, "items": [dict(i) for i in self.items]}

    def start(self, index: int) -> dict[str, Any]:
        for position, item in enumerate(self.items):
            if position < index:
                item["status"] = "completed"
            elif position == index:
                item["status"] = "in_progress"
        return self.event()

    def finish(self) -> dict[str, Any]:
        for item in self.items:
            item["status"] = "completed"
        return self.event()


async def _skill(name: str) -> AsyncIterator[dict[str, Any]]:
    """The supervisor reading /skills/<name>/SKILL.md — progressive disclosure."""
    await asyncio.sleep(_STEP_PAUSE)
    yield {"type": "skill", "id": str(new_id()), "skill": name}


async def _tool(
    name: str, detail: str, output: str, *, parent: str | None = None, pause: float = _TOOL_PAUSE
) -> AsyncIterator[dict[str, Any]]:
    run_id = str(new_id())
    start: dict[str, Any] = {
        "type": "tool_start",
        "id": run_id,
        "tool": name,
        "label": _LABELS.get(name, name.replace("_", " ").capitalize()),
        "detail": detail,
    }
    if parent:
        start["parent"] = parent
    yield start
    await asyncio.sleep(pause)
    yield {"type": "tool_end", "id": run_id, "tool": name, "output": output}


async def _delegate(
    agent: str, task: str, output: str, calls: list[tuple[str, str, str]]
) -> AsyncIterator[dict[str, Any]]:
    """A sub-agent run. Its own tool calls carry `parent` so the feed nests them."""
    run_id = str(new_id())
    yield {"type": "delegation", "id": run_id, "agent": agent, "task": task, "status": "running"}
    for name, detail, result in calls:
        async for event in _tool(name, detail, result, parent=run_id):
            yield event
    await asyncio.sleep(_TOOL_PAUSE)
    yield {"type": "delegation_end", "id": run_id, "output": output}


async def _stream_text(text: str) -> AsyncIterator[dict[str, Any]]:
    for token in re.findall(r"\S+\s*|\n", text):
        yield {"type": "token", "value": token}
        await asyncio.sleep(_TOKEN_PAUSE)


# ─────────────────────────── document generation ──────────────────────────


async def _generate(
    store: Store,
    *,
    owner_id: uuid.UUID,
    question: str,
    attachment_ids: list[uuid.UUID],
    template_key: str | None,
) -> AsyncIterator[dict[str, Any]]:
    catalogue = list(store.templates.values())
    template = next((t for t in catalogue if t.key == template_key), catalogue[0])
    sections = template.sections[:6]

    feed = Feed(
        [
            "Resolve the requested template",
            f"Retrieve evidence for {len(sections)} sections",
            "Delegate drafting to document_writer",
            "Assemble the deliverable and source coverage",
        ]
    )
    yield feed.event()
    async for event in _skill("document_generation"):
        yield event
    async for event in _skill("ecss_house_style"):
        yield event

    yield feed.start(0)
    async for event in _tool(
        "list_templates", "", f"{len(store.templates)} templates available"
    ):
        yield event
    async for event in _tool(
        "get_template",
        f"key: {template.key}",
        f"{template.name}"
        + (f" — {template.standard}" if template.standard else "")
        + f"\n{len(template.sections)} sections",
    ):
        yield event

    yield feed.start(1)
    evidence: dict[str, list[PageChunk]] = {}
    for section in sections:
        query = f"{section.get('title', '')} {section.get('guidance', '')}"
        hits = store.search(
            owner_id=owner_id, query=query, limit=3, file_ids=attachment_ids or None
        )
        evidence[section["title"]] = [page for page, _ in hits]
        output = (
            "\n".join(f"{_citation(p)} score {s}" for p, s in hits)
            if hits
            else "No indexed page matched."
        )
        async for event in _tool("search_pages", section["title"], output):
            yield event

    yield feed.start(2)
    cited = sum(len(pages) for pages in evidence.values())
    covered = [s for s in sections if evidence.get(s["title"])]
    async for event in _delegate(
        "document_writer",
        f"Draft {len(sections)} sections of “{template.name}” from "
        f"{cited} retrieved pages. Quote every citation.",
        f"{len(sections)} sections drafted, {cited} citations carried through.",
        [
            (
                "search_pages",
                f"{s['title']} (refining evidence)",
                "\n".join(_citation(p) for p in evidence[s["title"]]),
            )
            for s in covered[:2]
        ],
    ):
        yield event

    yield feed.start(3)
    for section in sections:
        path = f"/draft/{section.get('number', '0')}.md"
        async for event in _tool(
            "write_file", path, f"Wrote {path}", pause=_STEP_PAUSE / 2
        ):
            yield event
    async for event in _tool(
        "read_file", "/draft/*.md", f"{len(sections)} sections assembled in template order"
    ):
        yield event
    yield feed.finish()

    async for event in _stream_text(
        _render_document(template, sections, evidence, question, attachment_ids)
    ):
        yield event


def _render_document(
    template: Any,
    sections: list[dict[str, Any]],
    evidence: dict[str, list[PageChunk]],
    question: str,
    attachment_ids: list[uuid.UUID],
) -> str:
    parts = [f"# {template.name}"]
    if template.standard:
        parts.append(f"**Applicable standard:** {template.standard}")
    parts.append(f"**Prepared in response to:** {question.strip()[:240]}")
    parts.append("")

    coverage: list[str] = []
    for section in sections:
        number = section.get("number", "")
        title = section.get("title", "")
        pages = evidence.get(title, [])
        parts.append(f"## {number} {title}".strip())

        if pages:
            for page in pages:
                parts.append(
                    f"The source material records the following as applicable to this "
                    f"section: “{_excerpt(page)}” {_citation(page)}"
                )
                parts.append("")
            parts.append(
                f"{number}.1 The system shall satisfy the provisions recorded in "
                f"{_citation(pages[0])}. *Verification: Review of Design.*"
            )
            coverage.append(
                f"| {number} {title} | "
                + ", ".join(f"{p.filename} p.{p.page}" for p in pages)
                + " | Covered |"
            )
        else:
            parts.append(
                "[TBC] — no attached source addresses this section. Required input: "
                f"{section.get('guidance', 'supporting documentation')}"
            )
            coverage.append(f"| {number} {title} | — | [TBC] |")
        parts.append("")

    parts.append("## Source coverage")
    parts.append("")
    parts.append("| Section | Pages used | Status |")
    parts.append("| --- | --- | --- |")
    parts.extend(coverage)
    parts.append("")

    if not attachment_ids:
        parts.append(
            "> No documents were attached to this turn, so retrieval ran across the "
            "whole vault. Attach the specific sources to narrow the evidence base."
        )
    return "\n".join(parts) + FOOTER


# ──────────────────────────── feature comparison ──────────────────────────


def _verdict(score: float) -> tuple[str, str]:
    """Bands the retrieval score. Stands in for an analyst's judgement."""
    if score >= 0.55:
        return "COMPLIANT", "Source fully addresses the item."
    if score >= 0.32:
        return "PARTIAL", "Addressed, but the source is narrower than the target."
    if score > 0.0:
        return "NON-COMPLIANT", "Source addresses the topic with a conflicting value."
    return "NOT ADDRESSED", "No evidence in the sources."


def _item_text(page: PageChunk) -> str:
    """One checkable item per target page: its first requirement-shaped sentence."""
    sentences = [s.strip() for s in re.split(r"(?<=[.;])\s+", page.text) if s.strip()]
    preferred = next((s for s in sentences if " shall " in f" {s.lower()} "), None)
    chosen = preferred or (sentences[0] if sentences else page.text)
    return " ".join(chosen.split())[:200]


async def _compare(
    store: Store,
    *,
    owner_id: uuid.UUID,
    attachment_ids: list[uuid.UUID],
    target_id: uuid.UUID | None,
) -> AsyncIterator[dict[str, Any]]:
    source_ids = [i for i in attachment_ids if i != target_id]
    target_pages = store.file_pages(target_id) if target_id else []

    feed = Feed(
        [
            "Confirm target and sources",
            "Read the target and extract checkable items",
            "Retrieve evidence per item from the sources",
            "Delegate verdicts to comparison_analyst",
            "Render the compliance matrix",
        ]
    )
    yield feed.event()
    async for event in _skill("feature_comparison"):
        yield event

    target_name = target_pages[0].filename if target_pages else "none"
    source_names = [store.files[i].filename for i in source_ids if i in store.files]

    yield feed.start(0)
    async for event in _tool(
        "comparison_scope",
        "",
        f"Target: {target_name}\nSources ({len(source_names)}): "
        + (", ".join(source_names) or "none"),
    ):
        yield event

    if not target_pages:
        yield feed.finish()
        async for event in _stream_text(
            "No target document was designated for this comparison. Attach the "
            "baseline you want checked and mark it as the target in the composer, "
            "then attach the documents to check against it." + FOOTER
        ):
            yield event
        return

    yield feed.start(1)
    async for event in _tool(
        "load_target_document",
        target_name,
        f"{len(target_pages)} pages read, {len(target_pages)} checkable items extracted.",
    ):
        yield event

    yield feed.start(2)
    rows: list[dict[str, str]] = []
    for index, page in enumerate(target_pages, start=1):
        item = _item_text(page)
        hits = (
            store.search(owner_id=owner_id, query=item, limit=2, file_ids=source_ids)
            if source_ids
            else []
        )
        best_score = hits[0][1] if hits else 0.0
        verdict, note = _verdict(best_score)
        rows.append(
            {
                "id": f"TGT-{index:03d}",
                "requirement": item,
                "verdict": verdict,
                "evidence": ", ".join(_citation(p) for p, _ in hits) or "—",
                "notes": note,
                "target": _citation(page),
            }
        )
        async for event in _tool(
            "find_evidence_in_sources",
            f"TGT-{index:03d}: {item[:90]}",
            "\n".join(f"{_citation(p)} score {s}" for p, s in hits) or "No evidence found.",
        ):
            yield event

    yield feed.start(3)
    async for event in _delegate(
        "comparison_analyst",
        f"Assign verdicts to {len(rows)} items of {target_name} against "
        f"{len(source_names)} source document(s).",
        "\n".join(f"{r['id']} → {r['verdict']}" for r in rows[:12]),
        [
            (
                "find_evidence_in_sources",
                f"{r['id']}: re-checking the cited value",
                f"{r['evidence']} — {r['verdict']}",
            )
            for r in rows
            if r["verdict"] in {"PARTIAL", "NON-COMPLIANT"}
        ][:3],
    ):
        yield event

    yield feed.start(4)
    async for event in _tool(
        "build_compliance_matrix", f"{len(rows)} rows", f"Matrix rendered: {len(rows)} rows."
    ):
        yield event
    yield feed.finish()

    async for event in _stream_text(_render_matrix(rows, target_name, source_names)):
        yield event


def _render_matrix(
    rows: list[dict[str, str]], target_name: str, source_names: list[str]
) -> str:
    tally: dict[str, int] = {}
    for row in rows:
        tally[row["verdict"]] = tally.get(row["verdict"], 0) + 1

    parts = [
        "# Compliance matrix",
        "",
        f"**Target:** {target_name}  ",
        f"**Sources:** {', '.join(source_names) or 'none attached'}  ",
        f"**Items assessed:** {len(rows)}",
        "",
        "| ID | Target requirement | Verdict | Evidence | Notes |",
        "| --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        requirement = f"{row['requirement']} {row['target']}".replace("|", "\\|")
        parts.append(
            f"| {row['id']} | {requirement} | {row['verdict']} | "
            f"{row['evidence']} | {row['notes']} |"
        )

    parts += ["", "## Assessment", ""]
    order = ["COMPLIANT", "PARTIAL", "NON-COMPLIANT", "NOT ADDRESSED"]
    counts = " · ".join(f"**{k}**: {tally.get(k, 0)}" for k in order)
    parts.append(counts)
    parts.append("")
    blocking = tally.get("NON-COMPLIANT", 0) + tally.get("NOT ADDRESSED", 0)
    parts.append(
        f"{blocking} of {len(rows)} items are not satisfied by the attached sources "
        "and require either a waiver or a design change before the baseline can be "
        "accepted. Every COMPLIANT verdict above carries a page citation; open the "
        "cited page to verify it."
    )
    return "\n".join(parts) + FOOTER


# ─────────────────────────────── entrypoint ───────────────────────────────


async def run_turn(
    store: Store,
    *,
    owner_id: uuid.UUID,
    question: str,
    mode: str,
    attachment_ids: list[uuid.UUID],
    target_id: uuid.UUID | None,
    template_key: str | None,
) -> AsyncIterator[dict[str, Any]]:
    yield {"type": "status", "value": "running"}
    try:
        if mode == "feature_comparison":
            async for event in _compare(
                store, owner_id=owner_id, attachment_ids=attachment_ids, target_id=target_id
            ):
                yield event
        else:
            async for event in _generate(
                store,
                owner_id=owner_id,
                question=question,
                attachment_ids=attachment_ids,
                template_key=template_key,
            ):
                yield event
    except Exception as exc:  # noqa: BLE001 - surfaced as a feed row, as in production
        yield {"type": "error", "message": str(exc)[:500]}
    yield {"type": "status", "value": "done"}
