"""Wire contract — identical to backend/app/schemas.py by design."""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, EmailStr, Field

Mode = Literal["document_generation", "feature_comparison"]
Role = Literal["editor", "viewer"]


class ORMModel(BaseModel):
    model_config = ConfigDict(from_attributes=True)


# ───────────────────────────────── auth ──────────────────────────────────


class RegisterRequest(BaseModel):
    email: EmailStr
    password: str = Field(min_length=8, max_length=128)
    full_name: str = Field(default="", max_length=160)
    organisation: str = Field(default="", max_length=160)


class LoginRequest(BaseModel):
    email: EmailStr
    password: str


class UserOut(ORMModel):
    id: uuid.UUID
    email: EmailStr
    full_name: str
    organisation: str
    created_at: datetime


class TokenOut(BaseModel):
    access_token: str
    token_type: str = "bearer"
    user: UserOut


# ───────────────────────────────── files ─────────────────────────────────


class FileOut(ORMModel):
    id: uuid.UUID
    filename: str
    extension: str
    size_bytes: int
    page_count: int
    indexed: bool
    index_error: str | None
    comparison_role: str
    session_id: uuid.UUID | None
    created_at: datetime


# ─────────────────────────────── templates ───────────────────────────────


class TemplateSection(BaseModel):
    number: str = ""
    title: str
    guidance: str = ""


class TemplateCreate(BaseModel):
    name: str = Field(max_length=200)
    standard: str = Field(default="", max_length=120)
    description: str = ""
    sections: list[TemplateSection]


class TemplateOut(ORMModel):
    id: uuid.UUID
    key: str
    name: str
    standard: str
    description: str
    sections: list[dict[str, Any]]
    is_builtin: bool


# ───────────────────────────────── chat ──────────────────────────────────


class ChatRequest(BaseModel):
    message: str
    mode: Mode = "document_generation"
    session_id: uuid.UUID | None = None
    attachment_ids: list[uuid.UUID] = Field(default_factory=list)
    target_attachment_id: uuid.UUID | None = None
    template_key: str | None = None


class MessageOut(ORMModel):
    id: uuid.UUID
    role: str
    content: str
    mode: str | None
    activity: list[dict[str, Any]]
    attachments: list[dict[str, Any]]
    created_at: datetime


class SessionOut(ORMModel):
    id: uuid.UUID
    title: str
    mode: str
    created_at: datetime
    updated_at: datetime


class SessionDetail(SessionOut):
    messages: list[MessageOut] = Field(default_factory=list)


# ─────────────────────────────── documents ───────────────────────────────


class DocumentCreate(BaseModel):
    title: str = Field(default="Untitled document", max_length=300)
    content_json: dict[str, Any] | None = None


class DocumentFromMarkdown(BaseModel):
    title: str = Field(max_length=300)
    markdown: str
    commit_message: str = "Initial draft generated by aiper"


class CommitCreate(BaseModel):
    content_json: dict[str, Any]
    commit_message: str = Field(default="Update", max_length=500)


class DiffBlock(BaseModel):
    kind: Literal["equal", "add", "remove", "modify", "collapsed"]
    old_text: str | None = None
    new_text: str | None = None
    old_line: int | None = None
    new_line: int | None = None
    count: int | None = None


class DiffOut(BaseModel):
    additions: int = 0
    deletions: int = 0
    modifications: int = 0
    blocks: list[DiffBlock] = Field(default_factory=list)


class RevisionOut(ORMModel):
    id: uuid.UUID
    revision_number: int
    parent_revision_id: uuid.UUID | None
    commit_message: str
    source: str
    author_email: str
    author_name: str
    created_at: datetime
    additions: int = 0
    deletions: int = 0
    modifications: int = 0


class CollaboratorCreate(BaseModel):
    email: EmailStr
    role: Role = "editor"


class CollaboratorOut(ORMModel):
    id: uuid.UUID
    email: EmailStr
    role: str
    invite_status: str
    created_at: datetime


class DocumentOut(ORMModel):
    id: uuid.UUID
    title: str
    revision_count: int
    updated_at: datetime
    created_at: datetime
    access: str = "owner"
    owner_email: str = ""


class DocumentDetail(DocumentOut):
    content_json: dict[str, Any]
    revisions: list[RevisionOut] = Field(default_factory=list)
    collaborators: list[CollaboratorOut] = Field(default_factory=list)


class TitleUpdate(BaseModel):
    title: str = Field(max_length=300)
