# Aiper platform — one-shot demo setup (Windows).
#
#   irm https://raw.githubusercontent.com/DevDesai444/Aiper-platform/main/scripts/demo.ps1 | iex
#
# Needs: Docker Desktop installed (docker.com). Everything else is automatic.
# Safe to re-run.
$ErrorActionPreference = 'Stop'

function Say($m)  { Write-Host "`n> $m" -ForegroundColor Cyan }
function Fail($m) { Write-Host "`nX $m" -ForegroundColor Red; exit 1 }

$RepoUrl = 'https://github.com/DevDesai444/Aiper-platform.git'
$Dir     = Join-Path $HOME 'aiper-demo'
$SupabaseUrl = 'https://gawfzgnotbyjtkoxtbur.supabase.co'
$SupabaseKey = 'sb_publishable_yQVSqeDgnBm97E6zN9Nqkg_MTfsc1lE'

# -- git ---------------------------------------------------------------------
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Say 'Installing Git via winget'
    winget install --id Git.Git -e --accept-source-agreements --accept-package-agreements
    $env:Path = [Environment]::GetEnvironmentVariable('Path','Machine') + ';' + [Environment]::GetEnvironmentVariable('Path','User')
    if (-not (Get-Command git -ErrorAction SilentlyContinue)) { Fail 'Git installed but not on PATH yet - close this window, open a new PowerShell, re-run the same command.' }
}

# -- Docker ------------------------------------------------------------------
Say 'Checking Docker'
$dockerOk = $false
try { docker info *> $null; if ($LASTEXITCODE -eq 0) { $dockerOk = $true } } catch {}
if (-not $dockerOk) {
    $dd = Join-Path $env:ProgramFiles 'Docker\Docker\Docker Desktop.exe'
    if (Test-Path $dd) {
        Say 'Starting Docker Desktop (up to 2 minutes on first launch)'
        Start-Process $dd
        foreach ($i in 1..60) {
            Start-Sleep -Seconds 3
            try { docker info *> $null; if ($LASTEXITCODE -eq 0) { $dockerOk = $true; break } } catch {}
        }
    }
    if (-not $dockerOk) { Fail 'Docker is not available. Install Docker Desktop from https://docker.com, start it once, then re-run this command.' }
}

# -- code --------------------------------------------------------------------
if (Test-Path (Join-Path $Dir '.git')) {
    Say "Updating existing checkout at $Dir"
    git -C $Dir pull --ff-only
} else {
    Say "Cloning into $Dir"
    git clone --depth 1 $RepoUrl $Dir
}
Set-Location $Dir

# -- environment -------------------------------------------------------------
$envFile = Join-Path $Dir '.env'
if (-not (Test-Path $envFile)) {
    Say 'Writing .env (generated secrets; kept out of git)'
    $bytes = New-Object byte[] 32
    [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $jwt = ($bytes | ForEach-Object { $_.ToString('x2') }) -join ''
    @"
# Generated by scripts/demo.ps1 - local demo environment.
JWT_SECRET=$jwt

# Supabase identity (register with a real email; a confirmation mail follows).
SUPABASE_URL=$SupabaseUrl
NEXT_PUBLIC_SUPABASE_URL=$SupabaseUrl
NEXT_PUBLIC_SUPABASE_ANON_KEY=$SupabaseKey

# Optional - AI document generation stays off until these are filled:
# AZURE_OPENAI_API_KEY=
# AZURE_OPENAI_ENDPOINT=
# AZURE_OPENAI_API_VERSION=
# AZURE_OPENAI_CHAT_DEPLOYMENT_NAME=
# AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME=
"@ | Set-Content -Encoding ascii $envFile
} else {
    Say 'Reusing existing .env'
}

# -- build and start ---------------------------------------------------------
Say 'Building images (first run takes a few minutes)'
docker compose build
if ($LASTEXITCODE -ne 0) { Fail 'Image build failed - scroll up for the error.' }

Say 'Starting the stack'
docker compose up -d
if ($LASTEXITCODE -ne 0) { Fail 'Startup failed - try: docker compose logs' }

Say 'Waiting for the API (database migrates itself on first boot)'
$ok = $false
foreach ($i in 1..60) {
    try { $r = Invoke-WebRequest -UseBasicParsing -TimeoutSec 3 http://localhost:8000/health; if ($r.StatusCode -eq 200) { $ok = $true; break } } catch {}
    Start-Sleep -Seconds 3
}
if (-not $ok) { docker compose logs backend --tail 20; Fail 'API did not become healthy - logs above.' }

Say 'Waiting for the web app'
$ok = $false
foreach ($i in 1..40) {
    try { $r = Invoke-WebRequest -UseBasicParsing -TimeoutSec 3 http://localhost:3000; if ($r.StatusCode -eq 200) { $ok = $true; break } } catch {}
    Start-Sleep -Seconds 3
}
if (-not $ok) { Fail 'Web app did not come up; try: docker compose logs frontend' }

Say 'Aiper is running'
Write-Host @'

  Open:        http://localhost:3000
  First step:  "Create one" -> register with your real email
               (a confirmation mail follows - click it, then sign in)
  You get:     Projects -> folders/documents -> a full editor with comments,
               DOCX import/export and commit history. Access control and the
               audit trail are enforced by the database itself.

  Stop:   cd ~\aiper-demo ; docker compose down        (data survives)
  Reset:  cd ~\aiper-demo ; docker compose down -v     (wipes demo data)
'@
Start-Process 'http://localhost:3000'
