#!/usr/bin/env bash
# Aiper platform — one-shot demo setup.
#
#   curl -fsSL https://raw.githubusercontent.com/DevDesai444/Aiper-platform/main/scripts/demo.sh | bash
#
# Clones the repo, provisions a local environment, builds and starts the full
# stack (Postgres + Qdrant + API + web) in Docker, waits for health, and opens
# the app. Safe to re-run: it updates the checkout and reuses everything.
set -euo pipefail

REPO_URL="https://github.com/DevDesai444/Aiper-platform.git"
DIR="${AIPER_DEMO_DIR:-$HOME/aiper-demo}"

# Supabase identity for the demo project. The publishable key is exactly
# that — publishable; it ships in every client bundle by design.
SUPABASE_URL="https://gawfzgnotbyjtkoxtbur.supabase.co"
SUPABASE_PUBLISHABLE_KEY="sb_publishable_yQVSqeDgnBm97E6zN9Nqkg_MTfsc1lE"

say()  { printf '\n\033[1;36m▸ %s\033[0m\n' "$*"; }
fail() { printf '\n\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

command -v git >/dev/null || fail "git is required (macOS: xcode-select --install)"

# ── Docker ──────────────────────────────────────────────────────────────────
say "Checking Docker"
if ! docker info >/dev/null 2>&1; then
  if command -v colima >/dev/null; then
    say "Starting Colima (Docker VM)"
    colima start --cpu 4 --memory 6 --disk 40
  elif command -v brew >/dev/null; then
    say "Installing Docker (colima) via Homebrew — first run only, a few minutes"
    brew install colima docker docker-compose
    say "Starting Colima (Docker VM)"
    colima start --cpu 4 --memory 6 --disk 40
  else
    fail "Docker isn't running. Install Docker Desktop (docker.com) or Homebrew (brew.sh), then re-run this script."
  fi
  docker info >/dev/null 2>&1 || fail "Docker still isn't reachable after starting the VM."
fi

# ── Code ────────────────────────────────────────────────────────────────────
if [ -d "$DIR/.git" ]; then
  say "Updating existing checkout at $DIR"
  git -C "$DIR" pull --ff-only
else
  say "Cloning into $DIR"
  git clone --depth 1 "$REPO_URL" "$DIR"
fi
cd "$DIR"

# ── Environment ─────────────────────────────────────────────────────────────
if [ ! -f .env ]; then
  say "Writing .env (generated secrets; kept out of git)"
  JWT_SECRET="$(openssl rand -hex 32)"
  cat > .env <<EOF
# Generated by scripts/demo.sh — local demo environment.
JWT_SECRET=${JWT_SECRET}

# Supabase identity (register with a real email; a confirmation mail follows).
SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_PUBLISHABLE_KEY}

# Optional — AI document generation stays off until these are filled:
# AZURE_OPENAI_API_KEY=
# AZURE_OPENAI_ENDPOINT=
# AZURE_OPENAI_API_VERSION=
# AZURE_OPENAI_CHAT_DEPLOYMENT_NAME=
# AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME=
EOF
else
  say "Reusing existing .env"
fi

# ── Build and start ─────────────────────────────────────────────────────────
say "Building images (first run takes a few minutes)"
docker compose build

say "Starting the stack"
docker compose up -d

say "Waiting for the API (database migrates itself on first boot)"
for i in $(seq 1 60); do
  if curl -fsS http://localhost:8000/health >/dev/null 2>&1; then break; fi
  [ "$i" -eq 60 ] && { docker compose logs backend | tail -20; fail "API did not become healthy — logs above."; }
  sleep 3
done

say "Waiting for the web app"
for i in $(seq 1 40); do
  if curl -fsS -o /dev/null http://localhost:3000; then break; fi
  [ "$i" -eq 40 ] && fail "Web app did not come up; try: docker compose logs frontend"
  sleep 3
done

# ── Done ────────────────────────────────────────────────────────────────────
say "Aiper is running"
cat <<'EOF'

  Open:        http://localhost:3000
  First step:  “Create one” → register with your real email
               (Supabase sends a confirmation link — click it, then sign in)
  You get:     Projects → folders/documents → a full editor with comments,
               DOCX import/export and commit history. Access control and the
               audit trail are enforced by the database itself.

  AI document generation is the one dark feature — it lights up when Azure
  OpenAI keys are added to the .env in this folder (then: docker compose up -d).

  Stop:   cd ~/aiper-demo && docker compose down          (data survives)
  Reset:  cd ~/aiper-demo && docker compose down -v       (wipes demo data)
EOF
command -v open >/dev/null && open http://localhost:3000 || true
